name: Build Java Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Compilar e empacotar com Maven
        run: mvn clean package -DskipTests

      - name: Guardar artefacto (.jar)
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
          

