name: Build Java Project

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Compilar e empacotar com Maven
        run: mvn clean package -DskipTests -Dproject.build.sourceEncoding=UTF-8

      - name: Guardar artefacto (.jar)
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

      - name: Copiar .jar para o repositório
        run: |
          cp target/*.jar .
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add *.jar
          git commit -m "Add built jar via GitHub Actions" || echo "Nada para commitar"
          git push

