name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarQube:
    name: Run SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build with Maven
        run: mvn -B clean verify

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          args: >
            -Dsonar.projectKey=<NOME_DO_PROJETO_NO_SONARQUBE>
            -Dsonar.organization=<NOME_DA_ORGANIZACAO_SE_EXISTIR>
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # SONAR_HOST_URL é opcional — pode ser removido se indicado na tarefa
          # SONAR_HOST_URL: https://sonarcloud.io
